---

- name: Launch a job
  awx.awx.tower_job_launch:
    job_template: "{{ lookup('env','TOWER_JOB_TEMPLATE_NAME') }}"
  register: job

- name: Update AnsibleJob definition with Tower job id
  k8s:
    state: present
    definition:
      kind: AnsibleJob
      apiVersion: tower.ansible.com/v1alpha1
      metadata:
        name: "{{ lookup('env', 'ANSIBLEJOB_NAME') }}"
        namespace: "{{ lookup('env', 'ANSIBLEJOB_NAMESPACE') }}"
        labels:
          tower_job_id: "{{ job.id }}"

- name: Wait for job
  tower_job_wait:
    job_id: "{{ job.id }}"