---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jobs.tower.ansible.com
spec:
  group: tower.ansible.com
  names:
    kind: Job
    listKind: JobList
    plural: jobs
    singular: job
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
          description: Schema validation for the Tower Job Launch CRD
          properties:
            spec:
              type: object
              properties:
                tower_auth_secret:
                  type: string
                job_template_name:
                  type: string
          required:
            - tower_auth_secret
