---
# tasks file for jobtemplate

# - name: Show all vars
#   debug:
#     msg: "{{ vars }}"

- name: Read Secret Configuration
  k8s_info:
    kind: Secret
    namespace: '{{ meta.namespace }}'
    name: "{{ tower_auth_secret }}"
  register: tower_config_secret

- name: Generate a Pseudorandom K8s Job name
  set_fact:
    k8s_job_name: "{{ meta.name + '-' + (99999999 | random | to_uuid)[:8] }}"

- name: Start K8s Runner Job
  k8s:
    state: present
    definition: "{{ lookup('template', 'job_definition.yml') }}"

- name: Get Job Info
  k8s_info:
    api_version: batch/v1
    kind: Job
    name: "{{ k8s_job_name }}"
    namespace: "{{ meta.namespace }}"
  register: job_information_output

- name: Debug Job Information
  debug:
    var: job_information_output
